# SITE CONFIGURATION
title:  Grimsby and Immingham Karate Academy # your site title
author: Chris  # You :P
description: > # Meta description of Homepage
  Based in Grimsby, also with classes in Immingham, Lincs Karate is suitable for all ages and abilities.
  Sessions are in Traditional Shotokan Karate and Sport Karate.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.lincskarate.co.uk" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Lincs Karate
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Calendar', link: '/calendar'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Lincs Karate Academy is based in Grimsby & Immingham, with lessons in Traditional Shotokan &amp; Sport Karate. Sessions are suitable for all ages and abilities.

hero_img: posts/dojo.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: rdbingham14@gmail.com # email for form submission

facebook_username: Lincs-Karate-282664175889506 # replace with your_twitter_username or comment to remove link from footer
instagram_username: lincs_karate # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
